import { lstat, mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, relative, resolve } from 'node:path';
import type { Project } from '@shared/contracts.js';
import type { VaultEntry, VaultFileBinding } from '@shared/vault.js';
import { sameVaultFile, sanitizeVaultFileBinding } from '@shared/vault.js';
import { git } from '../git/run-git.js';

const MANAGED_HEADER =
  '# Generated by Oxum Vault. Plaintext: readable by processes in this project. Do not edit.\n';
const EXISTING_FILE_LIMIT = 1024 * 1024;

export interface VaultFileSource {
  entriesForFile(binding: VaultFileBinding, now: Date): Promise<readonly VaultEntry[]>;
}

export interface VaultFilesOptions {
  readonly vault: VaultFileSource;
  readonly projects: () => readonly Project[];
  readonly ignored?: (projectPath: string, relativePath: string) => Promise<boolean>;
  readonly tracked?: (projectPath: string, relativePath: string) => Promise<boolean>;
}

/**
 * Materializes encrypted Vault entries into project-owned dotenv files.
 *
 * The generated file is deliberately a derived artifact. It is written only inside a configured
 * project, only when Git ignores it, and only over a file carrying our marker. This prevents a
 * renderer payload from escaping the project or silently replacing a hand-written `.env`.
 */
export class VaultFiles {
  constructor(private readonly options: VaultFilesOptions) {}

  async generate(binding: VaultFileBinding): Promise<{ ok: boolean; message: string }> {
    try {
      return await this.generateChecked(binding);
    } catch (error) {
      console.error('[vault-files] generation failed', error);
      return { ok: false, message: 'The Vault file could not be generated.' };
    }
  }

  private async generateChecked(
    binding: VaultFileBinding,
  ): Promise<{ ok: boolean; message: string }> {
    const target = await this.target(binding);
    if ('message' in target) {
      return target;
    }
    const tracked = await (this.options.tracked ?? gitTracked)(
      target.project.path,
      target.binding.path,
    );
    if (tracked) {
      return {
        ok: false,
        message: `${target.binding.path} is already tracked by Git and was not touched.`,
      };
    }
    const ignored = await (this.options.ignored ?? gitIgnored)(
      target.project.path,
      target.binding.path,
    );
    if (!ignored) {
      return {
        ok: false,
        message: `${target.binding.path} is not ignored by Git. Add it to .gitignore first.`,
      };
    }
    const existing = await managedState(target.absolutePath);
    if (existing === 'other') {
      return {
        ok: false,
        message: `${target.binding.path} already exists and is not managed by Oxum Vault.`,
      };
    }
    if (existing === 'symlink') {
      return { ok: false, message: `${target.binding.path} is a symbolic link and was not touched.` };
    }

    const entries = await this.options.vault.entriesForFile(target.binding, new Date());
    if (entries.length === 0) {
      return { ok: false, message: 'This file has no live variables to generate.' };
    }
    const duplicate = duplicateVariable(entries);
    if (duplicate !== null) {
      return { ok: false, message: `${duplicate} appears more than once in this file.` };
    }
    await writeManagedFile(target.absolutePath, renderDotenv(entries));
    return {
      ok: true,
      message: `Generated ${target.binding.path} with ${String(entries.length)} variable${entries.length === 1 ? '' : 's'}.`,
    };
  }

  async remove(binding: VaultFileBinding): Promise<{ ok: boolean; message: string }> {
    try {
      return await this.removeChecked(binding);
    } catch (error) {
      console.error('[vault-files] removal failed', error);
      return { ok: false, message: 'The generated Vault file could not be removed.' };
    }
  }

  private async removeChecked(binding: VaultFileBinding): Promise<{ ok: boolean; message: string }> {
    const target = await this.target(binding);
    if ('message' in target) {
      return target;
    }
    const existing = await managedState(target.absolutePath);
    if (existing === 'missing') {
      return { ok: true, message: `${target.binding.path} is already absent.` };
    }
    if (existing !== 'managed') {
      return { ok: false, message: `${target.binding.path} is not managed by Oxum Vault.` };
    }
    await unlink(target.absolutePath);
    return { ok: true, message: `Removed generated file ${target.binding.path}.` };
  }

  /**
   * Removes expired/deleted values from files that were already generated.
   *
   * Missing files stay missing: saving a variable never materializes a secret without a click.
   */
  async sync(bindings: readonly VaultFileBinding[]): Promise<void> {
    const unique: VaultFileBinding[] = [];
    for (const binding of bindings) {
      if (!unique.some((entry) => sameVaultFile(entry, binding))) {
        unique.push(binding);
      }
    }
    for (const binding of unique) {
      try {
        const target = await this.target(binding);
        if ('message' in target || (await managedState(target.absolutePath)) !== 'managed') {
          continue;
        }
        const ignored = await (this.options.ignored ?? gitIgnored)(
          target.project.path,
          target.binding.path,
        );
        const tracked = await (this.options.tracked ?? gitTracked)(
          target.project.path,
          target.binding.path,
        );
        const entries = await this.options.vault.entriesForFile(target.binding, new Date());
        if (tracked || !ignored || entries.length === 0 || duplicateVariable(entries) !== null) {
          await unlink(target.absolutePath).catch(() => undefined);
          continue;
        }
        await writeManagedFile(target.absolutePath, renderDotenv(entries));
      } catch (error) {
        console.error('[vault-files] managed file sync failed', error);
      }
    }
  }

  private async target(binding: VaultFileBinding): Promise<
    | {
        binding: VaultFileBinding;
        project: Project;
        absolutePath: string;
      }
    | { ok: false; message: string }
  > {
    const parsed = sanitizeVaultFileBinding(binding);
    if (parsed === null) {
      return { ok: false, message: 'The project or output file is invalid.' };
    }
    const project = this.options.projects().find((entry) => entry.id === parsed.projectId);
    if (project === undefined) {
      return { ok: false, message: 'That project is no longer configured.' };
    }
    const root = resolve(project.path);
    const absolutePath = resolve(root, ...parsed.path.split('/'));
    const fromRoot = relative(root, absolutePath);
    if (fromRoot.length === 0 || fromRoot.startsWith('..') || isAbsolute(fromRoot)) {
      return { ok: false, message: 'The output file must stay inside the project.' };
    }
    if (!(await parentsAreRealDirectories(root, parsed.path))) {
      return { ok: false, message: 'The output path crosses a symbolic link and was not touched.' };
    }
    return { binding: parsed, project, absolutePath };
  }
}

async function gitIgnored(projectPath: string, relativePath: string): Promise<boolean> {
  try {
    await git(projectPath, ['check-ignore', '--quiet', '--no-index', '--', relativePath]);
    return true;
  } catch {
    return false;
  }
}

async function gitTracked(projectPath: string, relativePath: string): Promise<boolean> {
  try {
    await git(projectPath, ['ls-files', '--error-unmatch', '--', relativePath]);
    return true;
  } catch {
    return false;
  }
}

async function parentsAreRealDirectories(root: string, relativePath: string): Promise<boolean> {
  let current = root;
  const parts = relativePath.split('/');
  for (const part of parts.slice(0, -1)) {
    current = resolve(current, part);
    try {
      if ((await lstat(current)).isSymbolicLink()) {
        return false;
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return true;
      }
      throw error;
    }
  }
  return true;
}

async function managedState(
  path: string,
): Promise<'missing' | 'managed' | 'other' | 'symlink'> {
  try {
    const info = await lstat(path);
    if (info.isSymbolicLink()) {
      return 'symlink';
    }
    if (!info.isFile() || info.size > EXISTING_FILE_LIMIT) {
      return 'other';
    }
    return (await readFile(path, 'utf8')).startsWith(MANAGED_HEADER) ? 'managed' : 'other';
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return 'missing';
    }
    throw error;
  }
}

/**
 * Writes directly to the ignored target.
 *
 * The app's generic atomic writer uses a differently named sibling temp file. An exact ignore rule
 * such as `.env.local` would not cover that temp name, so a crash could leave a plaintext secret as
 * an untracked file. This file is derived from the encrypted vault and can be regenerated, making a
 * possible partial target safer than a second, non-ignored secret-bearing path.
 */
async function writeManagedFile(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, { encoding: 'utf8', flush: true });
}

function duplicateVariable(entries: readonly VaultEntry[]): string | null {
  const names = new Set<string>();
  for (const entry of entries) {
    const key = entry.card.name.toLowerCase();
    if (names.has(key)) {
      return entry.card.name;
    }
    names.add(key);
  }
  return null;
}

export function renderDotenv(entries: readonly VaultEntry[]): string {
  const lines = [MANAGED_HEADER.trimEnd(), ''];
  for (const entry of entries) {
    if (entry.card.hint.length > 0) {
      lines.push(`# ${entry.card.hint}`);
    }
    lines.push(`${entry.card.name}=${quoteDotenv(entry.value)}`, '');
  }
  return `${lines.join('\n')}\n`;
}

function quoteDotenv(value: string): string {
  return `"${value
    .replaceAll('\\', '\\\\')
    .replaceAll('"', '\\"')
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')}"`;
}
